
spring.application.name=Backend

# Server Configuration
server.port=8080

# Logging Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/notes_db
spring.datasource.username=llumiss
spring.datasource.password=kpi-diploma
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
# 'validate' or 'none' in production after initial setup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app.jwt.secret=63469bca0a457aff210ee1c12832c16e5f93b6b64303d72fbf32ebc69da181d65a9ac0a8e9f6c18508505cc2a72350e8f26df7008e86f9aa601d0bb62182be60
# 1 hour
app.jwt.access-token-expiration-ms=3600000
# 7 days
app.jwt.refresh-token-expiration-ms=604800000
